name: test ts files
on:
  push:
    branches:
      - master
jobs:
  build:
    name: jest
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn
      - run: yarn jest